### ISSUE TITLE
Issues when going to cart after upgrade to 1.2.5

### ISSUE THREAD

**Issue by jtalel** [coingate/magento2-plugin#10]
After update of Coingate Module via composer following error appears when going to /checkout/cart/    :

Fatal error: Uncaught Error: Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource in /var/www/html/magento2-site/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111 Stack trace: #0 /var/www/html/magento2-site/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) #1 /var/www/html/magento2-site/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...') #2 /var/www/html/magento2-site/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...') #3 /var/www/html/magento2-site/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('CoinGate\\Mercha...', Array) #4 /var/www/html/magento2-site/vendor/magento/module-payment/Model/Method/Factory.p in /var/www/html/magento2-site/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111

We even uninstalled the Coingate app and attempted to fresh install but same issue happened.

If more info is needed please reply this ticket. (No Report is found in /var/log )

**Comment by vgumonis** [comment]
Have you tried disabling the plugin and enabling it again using:
`php bin/magento module:enable CoinGate_Merchant --clear-static-content` and
`php bin/magento setup:upgrade`

After that it is advised to recreate your DI containers and clean the cache using:
`php bin/magento setup:di:compile`
`php bin/magento cache:clean`
`php bin/magento cache:flush`

If the issue still persists please provide us with the exact version of magneto you are using.

**Comment by jtalel** [comment]
Hello,

Issue persists. We currently have Magento 2.2.8. 

For further testing We proceeded to downgrade to Coingate 1.2.4 and fill in every single line modified in 1.2.5 and clean cache before insert next line. When following code (in bold):

     AbstractResource $resource = null,
        AbstractDb $resourceCollection = null,
        **_OrderManagementInterface $orderManagement,_**
        array $data = []

We get following error:

Fatal error: Uncaught TypeError: Argument 13 passed to CoinGate\Merchant\Model\Payment::__construct() must be an instance of Magento\Sales\Api\OrderManagementInterface, array given, called in /var/www/html/cauchosya228/generated/code/CoinGate/Merchant/Model/Payment/Interceptor.php on line 14 and defined in /var/www/html/cauchosya228/vendor/coingate/magento2-plugin/Model/Payment.php:67 Stack trace: #0 /var/www/html/cauchosya228/generated/code/CoinGate/Merchant/Model/Payment/Interceptor.php(14): CoinGate\Merchant\Model\Payment->__construct(Object(Magento\Framework\Model\Context), Object(Magento\Framework\Registry), Object(Magento\Framework\Api\ExtensionAttributesFactory), Object(Magento\Framework\Api\AttributeValueFactory), Object(Magento\Payment\Helper\Data\Interceptor), Object(Magento\Framework\App\Config), Object(Magento\Payment\Model\Method\Logger), Object(CoinGate\Merchant), Object(Magento\Framework\Url), Object(Magento\Store\Model\StoreManager), NULL, NULL, Array) #1 /var/www/html/cauchosya228/vendor/magento/framework in /var/www/html/cauchosya228/vendor/coingate/magento2-plugin/Model/Payment.php on line 67

**Comment by vgumonis** [comment]
It appears this was a version specific error. 

We have updated our module and tested it on Magento 2.2.8. 

You are welcome to update to version 1.2.6
