### ISSUE TITLE
When going to checkout in multi-currency site a 404 is displayed

### ISSUE THREAD

**Issue by jtalel** [coingate/magento2-plugin#11]
In a Magento 2.2.8 website, when going to checkout in a multicurreny website with USD as base price it will go to 404 page when display currency is not USD. 

I want to set coingate to always use base price. How can I achieve this?

**Comment by vgumonis** [comment]
Could you please provide the name of the currency you are experiencing trouble with.

CoinGate officially supported these currencies: https://coingate.com/currencies

**Comment by jtalel** [comment]
We're attempting to use VEF --> Venezuelan Bolivar.

But, base price for website is USD.  

You have a currency switcher on top of site. If you put USD it will allow checkout and if you put VEF it will show 404. If you do not support VEF We would like to customize Coingate to use base-currency (USD) no matter what display option the customer chooses. (if want to test check our dev site: https://bit.ly/2ZGa9Fg )

**Comment by vgumonis** [comment]
Sadly Venezuelan Bolivar is currently not supported by CoinGate.

We are always actively searching for new prospects regarding currencies available for pricing your merchandise, we will look into it further.

You can check our supported currencies here: https://coingate.com/currencies

You can follow our blog on https://blog.coingate.com/ and subscribe to our Facebook page to receive the latest updates about our products and services including Venezuelan Bolivar support.

Sincerely,
CoinGate
