### ISSUE TITLE
New version ??

### ISSUE THREAD

**Issue by angelflo** [coingate/magento2-plugin#13]
Hi,

It seems that you didin't publish update since more than one year.
Did you plan to update your magento extension and make it compatible with last magento version 2.4.1 ?
Any ETA ? or deprecated and you stop magento 2 support and dev ?

Thanks for the info, I'm currently migrate from magento1 to magento2.4.1 and would like to know if I can continue using your service or need to switch to another company because you stop magento2 dev.

**Comment by vgumonis** [comment]
Hi, 
We are planning on updating the magento extension alongside our other plugins during the first quarter of 2021

**Comment by angelflo** [comment]
Hi,

Any news about the update of your plugin and compatibility with Magento 2.4.2 ?

**Comment by jorgb90** [comment]
@vgumonis Any update after two years now?

**Comment by lseror** [comment]
what about after 3 years ?
