### ISSUE TITLE
Magento 2.4.4 Upgrade Error

### ISSUE THREAD

**Issue by anasshl** [coingate/magento2-plugin#14]
Hi,

after I upgraded Magento from 2.3.4-p1 to 2.4.4. I get the error bellow when I proceed to checkout page.
please I would like to know if the extension supports the latest version of Magento 2.4.4 with PHP 8.1?
and how could we fix this issue ?
![Coingate error](https://user-images.githubusercontent.com/36414706/169811211-656647dd-2b97-4f72-979a-ef45c32cd0f5.png)

Thank you,

**Comment by schossler** [comment]
waiting for 2.4.4 support ...

**Comment by anasshl** [comment]
if anyone is facing with the same error 

go to the  file vendor/coingate/magento2-plugin/Model/Payment.php
change the order in  constructor to 
  AbstractResource $resource = null,
  AbstractDb $resourceCollection = null,
 array $data = []
and change  line 137 from 'description' => join($description, ', '),  to  'description' => join(', ',$description),

**Comment by vgumonis** [comment]
thanks, this was fixed in a new release
