### ISSUE TITLE
When order expires it will cancel order but won't re-stock qty of products

### ISSUE THREAD

**Issue by jtalel** [coingate/magento2-plugin#9]
Current installed version of coingate: 1.2.4
Magento version: 2.2.8
LAMP 

When customer proceeds to checkout and selects coingate as payment method He will be sent to coingate for payment instructions. If customer doesn't pay and time expires the order will change status to Cancelled but products withing this order won't be cancelled. Products won't be re-stocked.

It also happens in sandbox when "Mark as Invalid" during Coingate checkout.

**Comment by vgumonis** [comment]
Thank you for your input. 

We recently updated our module updating the order canceling method for our callbacks.

Please, update your module via our GitHub page as the validation in the Magento marketplace can take up to 2 weeks.

**Comment by jtalel** [comment]
@vgumonis  Actually, once updating this module through composer I'm getting following error: https://prnt.sc/o1wnur

**Comment by vgumonis** [comment]
Have you tried disabling the plugin and enabling it again using:
 `php bin/magento module:enable CoinGate_Merchant --clear-static-content` and 
`php bin/magento setup:upgrade`

After that it is advised to recreate your DI containers and clean the cache using: 
`php bin/magento setup:di:compile` 
`php bin/magento cache:clean`
`php bin/magento cache:flush`

If nothing fixes the issue please provide us with the exact version of magneto you are using.
